name: "Dependapager"
author: " Shaik Ajmal R"
description: "A workflow action to send you weekly dependabot alerts to slack and create Jira tickets"
branding:
  icon: 'code'  
  color: 'green'
inputs:
  github_personal_token:
    description: " Github Personal Token to Query github for dependabot alerts"
    required: true
  slack_token:
    description: " Slack Bot Token to Send Alerts "
    required: true
  channel:
    description: " Slack Channel to Send the Alerts Too"
    required: true
  jira_token:
    description: " Token Required for quering JIRA REST API"
    required: true
  jira_url:
    description: " Your Organizations Jira Cloud URL"
    required: true
  jira_useremail:
    description: " Email id of the user associated with the token"
    required: true
  jira_project_key:
    description: " The Project Key for which Jira Tickets are created "
    required: true
  jira_issue_type:
    description: " Issue Type As Task or Epic or INC"
    required: true
outputs:
  total_alerts:
    description: "Total Open Alerts"
  critical_alerts:
    description: "Open Critical Alerts"
  high_alerts:
    description: "Open High Alertss"
  moderate_alerts:
    description: "Open Moderate Alerts"
  low_alerts:
    description: "Open Lower Alerts"
runs:
  using: 'docker'
  image: 'Dockerfile'


