name: "Dependaware"
author: "Adeniji Idris (Alvacoder)"
description: "A workflow action to send you weekly dependabot alerts to slack and create Linear issues (PS: More integrations to be added in future)"
branding:
  icon: 'code'  
  color: 'green'
inputs:
  github_personal_token:
    description: " Github Personal Token to Query github for dependabot alerts"
    required: true
  slack_token:
    description: " Slack Bot Token to Send Alerts "
    required: true
  channel:
    description: " Slack Channel to Send the Alerts Too"
    required: true
  linear_api_key:
    description: " Linear API Key Required for Linear GraphQL API"
    required: true
  linear_team_id:
    description: " Your Organizations Team ID to create issues for"
    required: true
outputs:
  total_alerts:
    description: "Total Open Alerts"
  critical_alerts:
    description: "Open Critical Alerts"
  high_alerts:
    description: "Open High Alertss"
  moderate_alerts:
    description: "Open Moderate Alerts"
  low_alerts:
    description: "Open Lower Alerts"
runs:
  using: 'docker'
  image: 'Dockerfile'


